[package]
name = "libblueprint"
version = "0.1.0"
authors = ["tmnosco"]
edition = "2018"

[dependencies]
libflate = "*"
base64 = "*"
json = "*"
libc = "*"

[lib]
name = "blueprint"
crate-type = ["cdylib"]
