[package]
name = "libblueprint"
version = "0.1.0"
authors = ["tmnosco"]

[dependencies]
libflate = "*"
base64 = "*"
json = "*"

[lib]
name = "blueprint"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]